defaults:
  - _self_

flair_embed:
  model_name: bert-base-uncased
  flair_layers: all
  flair_layer_mean: true

device: cuda:0
model: RNN
lr: 0.01
batch_size: 256
random_state: 1126

tuning:
  n_trials: 10

RNNFamily:
  hidden_size: 128
  num_layers: 1
  dropout: 0.0
  bidirectional: false

MLP:
  hidden_size: 256
  n_layers: 1
  dropout: 0.2
  output_size: 128

trainer:
  max_epochs: 2
  log_every_n_steps: 1
  check_val_every_n_epoch: 1